name: Hello world action
on: push
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$GMAP_KEY" > key'
        shell: bash
        env:
          GMAP_KEY: ${{secrets.GMAPAPI}}
