name: Hello world action
on: push
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          GMAPS_KEY: ${{ secrets.GMAPAPI }}
        run: |
              echo "$GMAPS_KEY" > key
